config/routes.rb
Testtask2::Application.routes.draw do

  root :to => 'events#index'

  resources :events do
    resources :comments, :only => [:create]
    collection do
      get 'bydate/:year/:month/:day/' => 'events#by_date'
    end
  end
  
  get 'myevents' => 'events#my'
  get 'myevents/bydate/:year/:month/:day/' => 'events#my_by_date'
  
  get 'profile' => 'users#show'
  put 'profile' => 'users#update'
  get 'profile/edit' => 'users#edit'

  get 'login' => 'users#login'
  post 'login' =>'users#process_login'  

  get 'register' => 'users#new'
  post 'register' => 'users#create'
  
  delete 'logout' => 'users#logout'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text

  belongs_to :user
  belongs_to :event
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :require_login

  def create # post /events/:event_id/comments
    @event = Event.find(params[:event_id])
    @comment = @event.comments.build(params[:comment])
    @comment.user_id = current_user_id

    unless @comment.save
      flash[:alert] = 'Error while saving comment'
    end
    redirect_to @event
  end

  private

  def require_login
    if user_not_logged_in?
      redirect_to login_path, :alert => 'Only registered users can comment events'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment"> 
  <div id="time">
    Posted at <%= comment.created_at %> by
  </div> 
  <div id="author">
    <%= comment.user.name %>:
  </div>
  <div id="text">
    <%= comment.text %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment, :url => event_comments_path(@event)) do |f| %>
  <div class="field">
    <%= f.label :text, 'Leave your comment:' %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit 'Post comment', :class => 'btn' %>
  </div>
<% end %>