config/routes.rb
Testtask2::Application.routes.draw do

  root :to => 'events#index'

  resources :events do
    resources :comments, :only => [:create]
    collection do
      get 'bydate/:year/:month/:day/' => 'events#by_date'
    end
  end
  
  get 'myevents' => 'events#my'
  get 'myevents/bydate/:year/:month/:day/' => 'events#my_by_date'
  
  get 'profile' => 'users#show'
  put 'profile' => 'users#update'
  get 'profile/edit' => 'users#edit'

  get 'login' => 'users#login'
  post 'login' =>'users#process_login'  

  get 'register' => 'users#new'
  post 'register' => 'users#create'
  
  delete 'logout' => 'users#logout'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :fullname, :password, :password_confirmation

  validates_presence_of :email, :password
  validates :email, :uniqueness => true
  validates :password, :confirmation => true
  validates :password, :length => { :in => 6..32 }

  has_many :events
  has_many :comments   

  require 'digest/md5'

  before_save do
    unless password_confirmation.nil?      
      self.password = Digest::MD5.hexdigest(self.password)
    end
  end

  def self.auth(auth_email, auth_password)
    find_by_email_and_password(auth_email, Digest::MD5.hexdigest(auth_password))
  end

  def name
    fullname.empty? ? email : fullname
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  ALREADY_LOGGED = 'You are already logged in'
  NOT_LOGGED = 'You are not logged in'

  before_filter :require_login, :except => [:login, :process_login, :new, :create]
  before_filter :require_no_login, :only => [:login, :process_login, :new, :create]

  def show # get /profile
    @user = current_user
    render
  end

  def login # get /login
    @user = User.new
    render
  end

  def process_login # post /login
    @user = User.auth(params[:user][:email], params[:user][:password])
    if @user.nil?
      flash[:alert] = 'Wrong email/password'
      @user = User.new
      render 'login'
    else
      session[:user] = @user.id
      redirect_to profile_path, :notice => 'Successfully logged in'
    end
  end

  def new # get /register
    @user = User.new
    render
  end

  def create # post /register
    @user = User.new(params[:user])
    if @user.save
      session[:user] = @user.id
      redirect_to profile_path, :notice => 'Successfully registered'
    else
      @user.errors.full_messages.each.with_index { |msg, index| flash[index] = msg }
      redirect_to register_path
    end
  end

  def update # put /profile
    @user = current_user
    if params[:user][:password].empty?
      params[:user][:password] = @user.password
      params[:user][:password_confirmation] = nil
    end
    if @user.update_attributes(params[:user])
      flash[:notice] = 'Changes saved'
    else
      @user.errors.full_messages.each.with_index { |msg, index| flash[index] = msg }
    end
    redirect_to profile_path
  end

  def logout # delete /logout
    session[:user] = nil
    redirect_to login_path
  end

  def edit # get /profile/edit by ajax
    @user = current_user
    render
  end

  private

  def require_login
    if user_not_logged_in?
      redirect_to login_path, :alert => NOT_LOGGED
    end
  end

  def require_no_login
    if user_logged_in?
      redirect_to profile_path, :alert => ALREADY_LOGGED
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, :url => urlaction ) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :fullname %><br />
    <%= f.text_field :fullname %>
  </div>
  <div class="actions">
    <%= f.submit savebutton, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user info</h1>

<%= link_to 'Cancel', profile_path, :class => 'btn btn-inverse' %>

<br/>

<b>If you don't want to change your password leave password field blank.</b>

<%= render :partial => 'form', :locals => { :urlaction => '/profile', :savebutton => 'Save user info' } %>

app/views/users/login.html.erb
<% content_for(:title) { " - Login"  } %>

<h1>Login</h1>


<%= form_for(@user, :url => '/login') do |f| %>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit 'Login', :class => 'btn large' %>
  </div>
<% end %>

<%= link_to 'Register', register_path %>

app/views/users/new.html.erb
<% content_for(:title) { " - Registration"  } %>

<h1>Register</h1>


<%= render :partial => 'form', :locals => { :urlaction => '/register', :savebutton => 'Register' } %>

<%= link_to 'Login', login_path %>

app/views/users/show.html.erb
<% content_for(:title) { " - #{ @user.name }'s profile" } %>

<div id="eventsheader">   
  <%= link_to 'All events', events_path, :class => 'btn small' %>
  <%= link_to 'My events', myevents_path, :class => 'btn small' %>
  <a href="#" class="btn small" id="by_date" data-date="<%= Date.today %>" data-date-format="yyyy-mm-dd">By date</a>  
</div> 
<hr/> 



<div id="profile">
  <h1>Your profile</h1>

  

  <%= link_to 'Edit info', "#", :id => "edit_info", :class => 'btn btn-warning' %>

    
  <p>
    <b>Email:</b>
    <div id="email">
      <%= @user.email %>
    </div>
  </p>

  <% unless @user.fullname.nil? || @user.fullname.empty? %>
    <p>
      <b>Fullname:</b>
      <div id="fullname">
        <%= @user.fullname %>
      </div>
    </p>
  <% end %>
</div>