config/routes.rb
Testtask2::Application.routes.draw do

  root :to => 'events#index'

  resources :events do
    resources :comments, :only => [:create]
    collection do
      get 'bydate/:year/:month/:day/' => 'events#by_date'
    end
  end
  
  get 'myevents' => 'events#my'
  get 'myevents/bydate/:year/:month/:day/' => 'events#my_by_date'
  
  get 'profile' => 'users#show'
  put 'profile' => 'users#update'
  get 'profile/edit' => 'users#edit'

  get 'login' => 'users#login'
  post 'login' =>'users#process_login'  

  get 'register' => 'users#new'
  post 'register' => 'users#create'
  
  delete 'logout' => 'users#logout'

end

app/models/event.rb
class Event < ActiveRecord::Base
  NO_PERIOD = 0
  DAILY = 1
  WEEKLY = 2
  MONTHLY = 3
  YEARLY = 4

  attr_accessible :date, :name, :period

  validates_presence_of :date, :name
  validates :period, :inclusion => { :in => 0..4 }

  before_save do
    period = NO_PERIOD if period.nil?      
  end

  belongs_to :user
  has_many :comments

  scope :before_date_and_with_period, lambda { |search_date, period| where('date < ? and period = ?', search_date, period) }

  def self.events_at(search_date)
    result = where(:date => search_date)

    result += before_date_and_with_period(search_date, DAILY)
    result += before_date_and_with_period(search_date, WEEKLY).select { |event| event.integer_weeks_to_date?(search_date) }
    result += before_date_and_with_period(search_date, MONTHLY).select { |event| event.integer_months_to_date?(search_date) }
    result += before_date_and_with_period(search_date, YEARLY).select { |event| event.integer_years_to_date?(search_date) }

    result
  end

  def integer_weeks_to_date?(end_date)
    result = (end_date - date).to_f / 7.0

    result == result.floor
  end

  def integer_months_to_date?(end_date)
    result = (end_date.year - date.year) * 12 + end_date.month - date.month

    if (date.day <= Time.days_in_month(end_date.month, end_date.year)) || 
       (end_date.day < Time.days_in_month(end_date.month, end_date.year))    
      result += (end_date.day - date.day) / 31.0
    end

    result == result.floor
  end

  def integer_years_to_date?(end_date)
    result = end_date.year - date.year

    bool = (end_date.month != date.month) ||
       (end_date.day != date.day) && ((end_date.month != 2) || Date.gregorian_leap?(end_date.year) || (date.day != 29) || (end_date.day != 28))             

    !bool
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  ONLY_REGISTERED = 'Only registered users can '

  before_filter :require_login
  before_filter :manage_only_own_events, :only => [:edit, :update, :destroy]
    
  def index # get /events
    @events = Event.all
    render :locals => { :all_events => true }
  end

  def my # get /myevents
    @events = current_user.events
    render 'index', :locals => { :all_events => false }
  end

  def show # get /events/:id
    @event = Event.find(params[:id])
    @comments = @event.comments
    @comment = Comment.new
    render
  end

  def new # get /events/new by ajax
    @event = Event.new
    render :partial => 'new'
  end

  def edit # get /events/:id/edit by ajax
    render :partial => 'edit'
  end

  def create # post /events
    @event = current_user.events.build(params[:event])

    if @event.save
      redirect_to @event, notice: 'Event was successfully created'
    else
      @event.errors.full_messages.each.with_index { |msg, index| flash[index] = msg }
      redirect_to events_path
    end
  end

  def update # put /events/:id
    if @event.update_attributes(params[:event])
      flash[:notice] = 'Changes saved'
    else
      @event.errors.full_messages.each.with_index { |msg, index| flash[index] = msg }
    end
    redirect_to @event
  end

  def destroy # delete /events/:id
    @event.destroy
    redirect_to :back, :notice => 'Event was succesfully deleted'
  end

  def by_date # get /events/bydate/:year/:month/:day/
    date = Date.new(params[:year].to_i, params[:month].to_i, params[:day].to_i)
    @events = Event.events_at(date)
    render 'index', :locals => { :all_events => true, :date => date }
  rescue ArgumentError
    redirect_to events_path, :alert => 'Wrong date'
  end

  def my_by_date # get /myevents/bydate/:year/:month/:day
    date = Date.new(params[:year].to_i, params[:month].to_i, params[:day].to_i)
    @events = current_user.events.events_at(date)
    render 'index', :locals => { :all_events => false, :date => date }
  rescue ArgumentError
    redirect_to myevents_path, :alert => 'Wrong date'
  end

  private

  def require_login
    if user_not_logged_in?
      redirect_to login_path, :alert => ONLY_REGISTERED + ' can view and manage events'
    end
  end

  def manage_only_own_events
    @event = Event.find(params[:id])

    if @event.user != current_user
      redirect_to @event, :alert => 'Users can manage only their events'
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def repeated(period)
    res = case period
          when Event::NO_PERIOD then ''
          when Event::DAILY then 'This event repeated every day.'
          when Event::WEEKLY then 'This event repeated every week.'
          when Event::MONTHLY then 'This event repeated every month.'
          when Event::YEARLY then 'This event repeated every year.'     
          end 
  end

  def my_event?(event)
    session[:user] == event.user_id
  end

  def convert_date(date)
    [date.year, date.month, date.day].join('/').html_safe
  end
end

app/views/events/_edit.html.erb
<h1>Editing event</h1>

<%= link_to 'Cancel and load event page', event_path(@event), :class => 'btn btn-inverse' %>


<%= render 'form' %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <div class="namefield">
    <%= f.label :name, 'Event name' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date, :id => 'datepicker', :readonly => true, :value => (@event.date.nil? ? Date.today : @event.date) %>
  </div>
  <div class="select">
    <%= f.label :period %><br/>
    <%= f.select :period, [['No period', 0], ['Daily', 1], ['Weekly', 2], ['Monthly', 3], ['Yearly', 4]] %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn' %>
  </div>
<% end %>

app/views/events/_new.html.erb
<h1>New event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<% content_for(:title) { " - #{ all_events ? 'All' : "#{ current_user.name }'s" } events #{ (defined? date) ? "at #{ date }" : '' }" } %>

<div id="eventsheader">   
  <%= link_to 'All events', ((defined? date) ?  "/events/bydate/#{ convert_date(date) }" : events_path), :class => "btn small#{ all_events ? ' btn-inverse' : '' }" %>
  <%= link_to 'My events', ((defined? date) ? "/myevents/bydate/#{ convert_date(date) }" : myevents_path), :class => "btn small#{ all_events ? '' : ' btn-inverse' }" %>
  <a href="#" class="btn small <%= (defined? date) ? 'btn-inverse' : '' %>" id="<%= all_events ? 'by_date' : 'my_by_date' %>" data-date="<%= (defined? date) ? date : Date.today %>" data-date-format="yyyy-mm-dd">By date<%= (defined? date) ? ": #{ date }" : '' %></a>  
  <%= (defined? date) ? (link_to 'Remove date filter', all_events ? events_path : myevents_path, :class => 'btn small') : '' %>
</div> 
<hr/> 

<h1>Showing <%= all_events ? 'all' : 'your' %> events <%= (defined? date) ? "at #{ date }" : '' %></h1>


<hr/>

<ul class="thumbnails">
  <li class="span3">
    <%= link_to (image_tag '/images/Plus_sign.png'), '#', :id => 'newevent', :class => 'thumbnail' %>
  </li>
<% @events.each do |event| %>
  <li class="span3">
    <div class="thumbnail">
      <div id="<%= event.id %>">
        <% if !all_events || my_event?(event) %>
          <%= link_to event.name, '#', :id => 'editevent', :class => 'btn btn-warning' %>
          <%= link_to 'Delete event', event, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-danger' %>
        <% else %>
          <%= event.name %>
        <% end %>
      </div>
      Date: <%= event.date %><br/>
      <%= repeated(event.period) %><br/>
      Author: <%= (!all_events || my_event?(event)) ? 'you' : event.user.name %><br/>
      <%= link_to event.comments.size.to_s + ' comments', event_path(event), :class => 'btn btn-success' %>
    </li>  
  <% end %>
  <% if @events.empty? %>
    <li class="span3">
      <div class="thumbnail">
        <b>
          <%= all_events ? 'No events have been created.' : 'You have no events.' %>        
        </b>
      </div>
    </li>
  <% end %>
</ul>


<br />


<div id="editform">
</div>

app/views/events/show.html.erb
<% content_for(:title) { " - Event #{ @event.name } comments"  } %>

<div id="eventsheader">   
  <%= link_to 'All events', events_path, :class => 'btn small' %>
  <%= link_to 'My events', myevents_path, :class => 'btn small' %>
  <a href="#" class="btn small" id="by_date" data-date="<%= Date.today %>" data-date-format="yyyy-mm-dd">By date</a>  
</div> 
<hr/> 

<div id="currentevent">
  
  <h1>Event <%= @event.name %></h1>
  
  
   <div id="<%= @event.id %>">
    <% if my_event?(@event) %>
      <%= link_to 'Edit', '#', :id => 'editcurrentevent', :class => 'btn btn-warning' %> | 
      <%= link_to 'Delete event', @event, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-danger' %>
    <% end %>
  </div>

  <p>
    <b>Date:</b>
    <%= @event.date %>
  </p>

  <div id="repeat">
    <%= repeated(@event.period) %>
  </div>
</div>

<hr/>

<%= render 'comments/form' %>

<h2>Comments:</h2>

<%= @comments.empty? ? 'There are no comments.' : '' %>
<%= render @comments %>