config/routes.rb
Testtask2::Application.routes.draw do

  root :to => 'events#index'

  resources :events do
    resources :comments, :only => [:create]
    collection do
      get 'bydate/:year/:month/:day/' => 'events#by_date'
    end
  end
  
  get 'myevents' => 'events#my'
  get 'myevents/bydate/:year/:month/:day/' => 'events#my_by_date'
  
  get 'profile' => 'users#show'
  put 'profile' => 'users#update'
  get 'profile/edit' => 'users#edit'

  get 'login' => 'users#login'
  post 'login' =>'users#process_login'  

  get 'register' => 'users#new'
  post 'register' => 'users#create'
  
  delete 'logout' => 'users#logout'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_logged_in? %>
    <li>
      <%= link_to('Logout', logout_path, :method => :delete) %>        
    </li>
  <% else %>
    <li>
    <%= link_to('Login', login_path)  %>  
    </li>
  <% end %>
  <% if user_logged_in? %>
    <li>
    <%= link_to('Profile', profile_path) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Register', register_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Events calendar<%= content_for?(:title) ? yield(:title) : '' %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>